name: "Publish"
on:
  workflow_dispatch:
jobs:
  release:
    name: "Pack & Upload"
    runs-on: ubuntu-latest
    steps:
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: quickcheck-dynamic.tar.gz
        path: ${{ matrix.project }}
    - uses: haskell-actions/hackage-publish@v1
      with:
        hackageToken: ${{ secrets.HACKAGE_AUTH_TOKEN }}
        packagesPath: '.'
        publish: false
